# ----------------------------------------------------------------------
# Written by Raph.K.
#

# Compiler preset.
CC_PREFIX = $(PREFIX)
CC_PATH =

GCC = $(CC_PATH)$(CC_PREFIX)gcc
GPP = $(CC_PATH)$(CC_PREFIX)g++
AR  = ar
FCG = fltk-config --use-images

# FLTK configs 
FLTKCFG_CXX := $(shell ${FCG} --cxxflags)
FLTKCFG_LFG := $(shell ${FCG} --ldflags)

# Base PATH
BASE_PATH = .
LIB_PATH  = $(BASE_PATH)/lib
SRC_PATH  = $(BASE_PATH)/src

# TARGET settings
TARGET_PKG = srcnntest
TARGET_DIR = ./bin
TARGET_OBJ = ./obj/test

# DEFINITIONS
DEFS  = -DFORTESTINGBIN -DEXPORTLIB

# Compiler optiops 
COPTS  = 
COPTS += -ffast-math -fexceptions -fopenmp -O3 -s
COPTS += $(FLTKCFG_CXX)

# CC FLAG
CFLAGS  = -I$(SRC_PATH)
CFLAGS += -I$(LIB_PATH)
CFLAGS += -I../fl_imgtk/lib
CFLAGS += $(DEFS)
CFLAGS += $(COPTS)

# LINK FLAG
LFLAGS  = 
LFLAGS += -L$(LIB_PATH)
LFLAGS += -L../fl_imgtk/lib
LFLAGS += -lfl_imgtk
LFLAGS += $(FLTKCFG_LFG)
LFLAGS += -lsrcnn
LFLAGS += -lpthread

SRC = $(SRC_PATH)/test.cpp $(SRC_PATH)/tick.cpp

.PHONY: prepare clean

all: prepare clean continue

continue: $(TARGET_DIR)/$(TARGET_PKG)

prepare:
	@mkdir -p $(TARGET_DIR)
	@mkdir -p $(TARGET_DIR)/res
	@mkdir -p $(TARGET_OBJ)

clean:
	@echo "Cleaning built targets ..."
	@rm -rf $(TARGET_DIR)/$(TARGET_PKG)
	@rm -rf $(TARGET_INC)/*.h
	@rm -rf $(TARGET_OBJ)/*.o

$(TARGET_DIR)/$(TARGET_PKG): $(OBJS)
	@echo "Compiling $@ ..."
	@$(GPP) $(SRC) $(CFLAGS) $(LFLAGS) -o $@
	@echo "done."
